FROM registry.access.redhat.com/ubi8/ruby-25

ARG APP_USER=appuser
ARG APP_GROUP=appgroup
ARG APP_DIR=/blog

USER root
RUN yum update --disablerepo=* --enablerepo=ubi-8-appstream --enablerepo=ubi-8-baseos -y && rm -rf /var/cache/yum
RUN yum install --disablerepo=* --enablerepo=ubi-8-appstream --enablerepo=ubi-8-baseos sqlite -y && rm -rf /var/cache/yum
RUN groupadd -r $APP_GROUP && \
    useradd -M -r --uid 101 -g $APP_GROUP $APP_USER && \
    mkdir $APP_DIR && \
    chown $APP_USER:$APP_GROUP $APP_DIR 

RUN gem update --system 3.1.2 &&\
    gem install bundler -v '2.1.2'

USER $APP_USER
WORKDIR $APP_DIR

COPY --chown=$APP_USER:$APP_GROUP --from=purpledobie/blog:gems-good /blog .

ENV BUNDLER_VERSION 2.1.2
ENV RAILS_ENV=development
RUN bundle config --local path vendor/bundle && bundle config --local without assets &&\
    bundle exec rails db:setup &&\
    bundle exec rails db:migrate

EXPOSE 3000

CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
