# def snyk(path, name='snyk'):
#     """
#     Args:
#       path: path to file to test
#       name: a name for the resource, defaults to snyk. Useful if you want multiple invocations
#     """
#     local_resource(
#         name,
#         deps=[path],
#         cmd= 'snyk iac test %s' % (path)
#     )


def snyk_i(name, 
         path):
    """
    Args:
      name: the name of this tilt resource (what you'll see in Tilt's sidebar)
      path: path to file to test
            - container: path is the image name and tag (image:tag)
            - iac: the name of the file to test (deployment.yaml)
            - oss: path to search. oss uses '--all-projects' by default right now
      test_type: one of 'container', 'iac', or 'oss'. Determines which test to run.
      dfile: (optional) the Dockerfile to test with a container test
    """       

  snyk_test_cmd = " ".join([
      "snyk iac test",
      path
  ])

  local_resource(
    name,
    deps=[path],
    cmd= snyk_test_cmd,
    trigger_mode=TRIGGER_MODE_MANUAL
  )


def snyk_c(name, 
           path, 
           *dfile):
    """
    Args:
      name: the name of this tilt resource (what you'll see in Tilt's sidebar)
      path: path to file to test
            - container: path is the image name and tag (image:tag)
      dfile: (optional) the Dockerfile to test with a container test; if blank then run a standard test
    """
  snyk_test_cmd = " ".join([
      "snyk container test",
      path
  ])

  
  if isInstance(dfile[0],str): 
       snyk_test_cmd += " file=" + dfile[0] 
  
  

  local_resource(
      name,
      resource_deps=[resource_name],
      cmd=snyk_test_cmd,
      trigger_mode=TRIGGER_MODE_MANUAL
  )



def snyk_o(name, 
           path):
    """
    Args:
      name: the name of this tilt resource (what you'll see in Tilt's sidebar)
      path: path to files to test
            - oss: path to search. using '--all-projects' by default for now
    """
  snyk_test_cmd = " ".join([
      "snyk test",
      path,
      "--all-projects"
  ])

  local_resource(
      name,
      deps=[path],
      cmd= snyk_test_cmd,
      trigger_mode=TRIGGER_MODE_MANUAL
  )
